### ISSUE TITLE
Handle multi-bar charts

### ISSUE THREAD

**Issue by Koleok** [iSCAD-plus/plots-prototype#6]
Handle charts with stacked series data and render correct colors/legends, basically just reproduce the [`multiBar example`](http://nvd3.org/examples/multiBar.html)

**Comment by ntietz** [comment]
@Koleok As far as I can tell, this is done now. We've both been kind of code reviewing as we went. If you have any changes you want in my latest push, let me know, otherwise we can probably merge.
