### ISSUE TITLE
Create additional plot definitions 

### ISSUE THREAD

**Issue by Koleok** [iSCAD-plus/plots-prototype#7]
Specifically need the following titles from `sanctions_regimes_graphs.pdf`

- [x] Security Council sanctions-related decisions by year
- [x] Amendments to sanctions measures by year
- [x] Amendments to sanctions measures by year
- [ ] Security Council sanctions-related decisions by measure
- [ ] Amendments to sanctions measures by type
- [ ] Security Council sanctions-related decisions by regime
- [ ] Amendments to sanctions measures by regime
- [ ] Amendments to sanctions measures by regime
- [ ] Security Council sanctions-related decisions by type
- [ ] Amendments to sanctions measures by type
- [ ] Security Council sanctions-related decisions by month
- [ ] Paragraphs per Security Council sanctions-related decision
- [ ] Security Council sanctions-related decisions
- [ ] Arms embargo
- [ ] Assets freeze
- [ ] Travel ban or restrictions
- [ ] Security Council sanctions- related decisions by type
- [ ] Security Council sanctions-related decisions by year
- [ ] Security Council sanctions-related decisions by measure
- [ ] Amendments to sanctions measures by type
- [ ] Amendments to sanctions measures by type
- [ ] Amendments to sanctions measures by year
- [ ] Security Council sanctions-related decisions by month
- [ ] Paragraphs per Security Council sanctions-related decision
- [ ] Security Council sanctions-related decisions
- [ ] Arms embargo
- [ ] Assets freeze
- [ ] Ban on export of arms by target state
- [ ] Chemical and biological weapons embargo
- [ ] Diplomatic or overseas representation restrictions
- [ ] Embargo on natural resources
- [ ] Financial restrictions
- [ ] Luxury goods embargo
- [ ] Non-proliferation measures
- [ ] Prohibition on bunkering services
- [ ] Public financial support for trade restrictions
- [ ] Restrictions on ballistic missiles
- [ ] Trade embargo
- [ ] Travel ban or restrictions
- [ ] Security Council sanctions-related decisions by type
- [ ] Security Council sanctions-related decisions by year
- [ ] Security Council sanctions-related decisions by month
- [ ] Security Council sanctions-related decisions by measure
- [ ] Paragraphs per Security Council sanctions-related decision
- [ ] Amendments to sanctions measures by type
- [ ] Amendments to sanctions measures by year

**Comment by ntietz** [comment]
@Koleok are we looking at the same document? these titles don't match what I see here http://www.un.org/en/sc/repertoire/data/sanctions_regimes_graphs.pdf

**Comment by ntietz** [comment]
~New features needed for "J. Average length of Security Council sanctions-related decisions" (page 12)~
done

**Comment by ntietz** [comment]
New features needed for page 13, 14

**Comment by ntietz** [comment]
~New features needed for "J. Average length of Security Council sanctions-related decisions" (page 18)~
done

**Comment by ntietz** [comment]
@Koleok what is the effort required to get timelines working?

**Comment by Koleok** [comment]
Man I need some kind of push notification for these, i guess it was a pretty absentee weekend for me though.

**Comment by Koleok** [comment]
@ntietz FWIW I think we'll end up with something between [this](http://nvd3.org/examples/bullet.html) and [this](https://github.com/jiahuang/d3-timeline)
